export const all_american_states = [
    "Alabama",
    "Alaska",
    "Arizona",
    "Arkansas",
    "California",
    "Colorado",
    "Connecticut",
    "Delaware",
    "Florida",
    "Georgia",
    "Hawaii",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Maine",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Montana",
    "Nebraska",
    "Nevada",
    "New Hampshire",
    "New Jersey",
    "New Mexico",
    "New York",
    "North Carolina",
    "North Dakota",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Pennsylvania",
    "Rhode Island",
    "South Carolina",
    "South Dakota",
    "Tennessee",
    "Texas",
    "Utah",
    "Vermont",
    "Virginia",
    "Washington",
    "West Virginia",
    "Wisconsin",
    "Wyoming",
];

export const unsupported_american_states = [
    "Washington",
    "Oregon",
    "California",
    "Nevada",
    "Idaho",
    "Montana",
    "Wyoming",
    "Alaska",
    "South Dakota",
    "North Dakota",
    "Arizona",
    "Hawaii",
];

export const eastus = [
    "Maine",
    "New Hampshire",
    "Massachusetts",
    "New York",
    "Vermont",
    "Rhode Island",
    "Connecticut",
    "New Jersey",
    "Delaware",
    "Maryland",
    "Pennsylvania",
    "Virginia",
    "West Virginia",
    "North Carolina",
    "South Carolina",
    "Georgia",
    "Florida",
    "Alabama",
];

export const southcentralus = [
    "Texas",
    "Arkansas",
    "Oklahoma",
    "New Mexico",
    "Louisiana",
    "Colorado",
];

export const northcentralus = [
    "Illinois",
    "Ohio",
    "Indiana",
    "Kentucky",
    "Michigan",
    "Tennessee",
    "Wisconsin",
    "Minnesota",
    "Iowa",
    "Missouri",
    "Mississippi",
    "Kansas",
    "Nebraska",
];