export const apps = [
    {
        name: "Google Chrome",
        category: "Productivity",
        image: "chrome.svg",
        link: "https://www.google.com/chrome/",
        size: 30.3,
    },
    {
        name: "Firefox",
        category: "Productivity",
        image: "firefox.png",
        link: "https://www.mozilla.org/en-US/firefox/new/",
        size: 66.1,
    },
    {
        name: "VLC media player",
        category: "Productivity",
        image: "vlc.png",
        link: "https://www.videolan.org/vlc/index.html",
        size: 40.08,
    },
    {
        name: "Adobe Acrobat",
        category: "Productivity",
        image: "acrobat.png",
        link: "https://acrobat.adobe.com/us/en/acrobat/pdf-reader.html",
        size: 170,
    },
    {
        name: "Dropbox",
        category: "Productivity",
        image: "dropbox.png",
        link: "https://www.dropbox.com/",
        size: 511,
    },
    {
        name: "Microsoft Office",
        category: "Productivity",
        image: "office.png",
        link: "https://www.office.com/",
        size: 4000,
    },
    {
        name: "Spotify",
        category: "Productivity",
        image: "spotify.png",
        link: "https://www.spotify.com/us/",
        size: 188,
    },
    {
        name: "Zoom",
        category: "Communication",
        image: "zoom.png",
        link: "https://www.zoom.us/",
        size: 58,
    },
    {
        name: "Skype",
        category: "Communication",
        image: "skype.png",
        link: "https://www.skype.com/en/",
        size: 220,
    },
    {
        name: "WhatsApp",
        category: "Communication",
        image: "whatsapp.png",
        link: "https://www.whatsapp.com/",
        size: 37,
    },
    {
        name: "Telegram",
        category: "Communication",
        image: "telegram.png",
        link: "https://telegram.org/",
        size: 71,
    },
    {
        name: "Discord",
        category: "Communication",
        image: "discord.png",
        link: "https://discord.com/",
        size: 160,
    },
    {
        name: "Steam",
        category: "Gaming",
        image: "steam.png",
        link: "https://store.steampowered.com/",
        size: 1100,
    },
    {
        name: "Epic Games",
        category: "Gaming",
        image: "epic_games.png",
        link: "https://www.epicgames.com/store/en-US/",
        size: 1000,
    },
    {
        name: "GeForce Experience",
        category: "Gaming",
        image: "geforce.png",
        link: "https://www.nvidia.com/en-us/geforce/geforce-experience/",
        size: 117,
    },
    {
        name: "GOG",
        category: "Gaming",
        image: "gog.png",
        link: "https://www.gog.com/",
        size: 213,
    },
    {
        name: "Blender",
        category: "Creative",
        image: "blender.png",
        link: "https://www.blender.org/",
        size: 200,
    },
    {
        name: "Gimp",
        category: "Creative",
        image: "gimp.png",
        link: "https://www.gimp.org/",
        size: 85.4,
    },
    {
        name: "Cinema4D",
        category: "Creative",
        image: "cinema_4d.png",
        link: "https://www.maxon.net/en-us/products/cinema-4d/overview/",
        size: 850,
    },
    {
        name: "Lightworks",
        category: "Creative",
        image: "lightworks.png",
        link: "https://www.lwks.com/",
        size: 310,
    },
    {
        name: "Autodesk Fusion 360",
        category: "Creative",
        image: "fusion.png",
        link: "https://www.autodesk.com/products/fusion-360/overview",
        size: 3100,
    },
    {
        name: "Git",
        category: "Developer",
        image: "git.png",
        link: "https://git-scm.com/",
        size: 572,
    },
    {
        name: "Atom",
        category: "Developer",
        image: "atom.png",
        link: "https://atom.io/",
        size: 180,
    },
    {
        name: "Node.js",
        category: "Developer",
        image: "nodejs.png",
        link: "https://nodejs.org/",
        size: 50,
    },
    {
        name: "Android Studio",
        category: "Developer",
        image: "android_studio.png",
        link: "https://developer.android.com/studio",
        size: 1000,
    },
    {
        name: "GitHub Desktop",
        category: "Developer",
        image: "github_desktop.png",
        link: "https://desktop.github.com/",
        size: 90,
    },
    {
        name: "Unity",
        category: "Developer",
        image: "unity.png",
        link: "https://unity.com/",
        size: 10000,
    },
    {
        name: "Sublime Text 3",
        category: "Developer",
        image: "sublimetext.png",
        link: "https://www.sublimetext.com/",
        size: 35,
    },
    {
        name: "OpenCV",
        category: "Developer",
        image: "opencv.png",
        link: "https://opencv.org/",
        size: 593,
    },
    {
        name: "CUDA Development Toolkit",
        category: "Developer",
        image: "cuda.jpeg",
        link: "https://developer.nvidia.com/cuda-zone",
        size: 60,
    },
    {
        name: "LLVM",
        category: "Developer",
        image: "llvm.png",
        link: "https://llvm.org/",
        size: 500,
    },
    {
        name: "Anaconda",
        category: "Developer",
        image: "anaconda.png",
        link: "https://www.anaconda.com/",
        size: 5000,
    },
    {
        name: "Docker",
        category: "Developer",
        image: "docker.png",
        link: "https://www.docker.com/",
        size: 2500,
    },
    {
        name: "cURL",
        category: "Developer",
        image: "curl.png",
        link: "https://curl.haxx.se/",
        size: 4,
    },
    {
        name: "CMake",
        category: "Developer",
        image: "cmake.png",
        link: "https://cmake.org/",
        size: 90,
    },
    {
        name: "Visual Studio Code",
        category: "Developer",
        image: "vscode.png",
        link: "https://code.visualstudio.com/",
        size: 500,
    },
    {
        name: "Visual Studio 2019",
        category: "Developer",
        image: "vs_pro.png",
        link: "https://visualstudio.microsoft.com/vs/professional/",
        size: 3500,
    },
    {
        name: "Visual C++ Redistribuable",
        category: "Developer",
        image: "visual_redist.png",
        link:
            "https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads",
        size: 50,
    },
    {
        name: "Cppcheck",
        category: "Developer",
        image: "cppcheck.png",
        link: "http://cppcheck.sourceforge.net/",
        size: 10,
    },
    {
        name: "7-Zip",
        category: "Developer",
        image: "7zip.png",
        link: "https://www.7-zip.org/",
        size: 10,
    },
    {
        name: "Windows Subsystem for Linux",
        category: "Developer",
        image: "wsl.png",
        link: "https://docs.microsoft.com/en-us/windows/wsl/install-win10",
        size: 2000,
    },
];
